version: "2"
services:
  consul-node0:
    image: "consul:latest"
    container_name: "node0"
    hostname: "node0"
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600/udp:8600/udp"
    - "8600/tcp:8600/tcp"
    command: "agent -server -client=0.0.0.0 -node=node0 --bootstrap-expect=1 -bind=172.16.238.10 -ui -log-level=debug" 
    networks:
      consul_net:
        ipv4_address: 172.16.238.10 

  consul-node1:
    image: "consul:latest"
    container_name: "node1"
    hostname: "node1"
    command: "agent -server -client=0.0.0.0 -node=node1 -bind=172.16.238.11 -join=172.16.238.10"
    networks:
      consul_net:
        ipv4_address: 172.16.238.11

  consul-node2:
    image: "consul:latest"
    container_name: "node2"
    hostname: "node2"
    command: "agent -server -client=0.0.0.0 -node=node2 -bind=172.16.238.12 -join=172.16.238.10"
    networks:
      consul_net:
        ipv4_address: 172.16.238.12 

  #registrator:
  #  image: "gliderlabs/registrator:latest"
  #  container_name: "registrator"
  #  hostname: "registrator"
  #  command: "consul://localhost:8500"
  #  volumes: 
  #  - /var/run/docker.sock:/tmp/docker.sock
  #  network_mode: "host"

networks:
  consul_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
